#install dependencies: 
#Microsoft Visual C++ Compiler for Python 2.7 at https://www.microsoft.com/en-ca/download/details.aspx?id=44266
#c:\>conda install MinGW
#c:\>conda install libpython
package:
  name: pygslib
  version: "0.0.0.3.7.2"

source:
  path: c:/OG_Python/pygslib/
  

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pygslib = pygslib:main
    #
    # Would create an entry point called pygslib that calls pygslib.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - mingw
    - libpython
    - python
    - setuptools
    - numpy 
    - pandas
    - matplotlib
    - nose
    - mock
    - scipy

  run:
    - python
    - numpy
    - pandas
    - matplotlib
    - nose
    - mock
    - scipy
    - vtk
    - ipython
    - pyevtk
    - mingw
    - libpython

test:
  # Python imports
  imports:
    - pygslib

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - matplotlib
    - mock
    - nose
    - numpy
    - pandas
    - scipy
    - mingw
    - libpython
    
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/opengeostat/pygslib
  license: MIT License
  summary: 'Python wrap of GSLIB modified code and general geostatistical package'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
