#install dependencies: 
#Microsoft Visual C++ Compiler for Python 2.7 at https://www.microsoft.com/en-ca/download/details.aspx?id=44266
#c:\>conda install MinGW
#c:\>conda install libpython
package:
  name: pygslib
  version: "0.0.0.3.8.4"

source:
  path: ../../
  

build:
  script: python setup.py config --compiler=mingw32 build --compiler=mingw32 install


requirements:
  build:
    - mingw
    - libpython ==1.0 
    - python
    - setuptools
    - numpy 
    - pandas >=0.17
    - matplotlib
    - scipy
    - vc ==9
    - vs2008_runtime

  run:
    - python
    - numpy
    - pandas >=0.17
    - matplotlib
    - scipy
    - vtk  >=6
    - ipython
    - pyevtk
    - color
    - mingw
    - libpython ==1.0 



about:
  home: https://github.com/opengeostat/pygslib
  license: MIT License
  summary: 'Python wrap of GSLIB modified code and general geostatistical package'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml